In [222]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import seaborn as sns
import random
import pygame
from sklearn.metrics import silhouette_samples, silhouette_score

In [223]:
data = pd.read_csv('C://Shaurya Games//New folder//fashion-mnist_train.csv')

data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [224]:
def ReLU(Z):
    return np.maximum(Z, 0)

def ReLU_deriv(Z):
    return Z > 0

In [225]:
def softmax(A):
    
    expA = np.exp(A)
    return expA / sum(np.exp(A))

In [226]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [227]:
def init_params():
    W1 = np.random.rand(50, 784) * 1/math.sqrt(784)
    b1 = np.random.rand(50, 1) * 1/math.sqrt(784)
    W2 = np.random.rand(10, 50) * 1/math.sqrt(10)
    b2 = np.random.rand(10, 1) * 1/math.sqrt(10)
        
    return W1, b1, W2, b2
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
    
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2
    
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
        
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2
    
def get_predictions(A2):
    return np.argmax(A2, 0)

In [228]:
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size


In [229]:
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [230]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[6 6 6 ... 6 6 6] [1 6 7 ... 1 9 5]
0.09972881355932203
Iteration:  10
[9 2 9 ... 1 9 9] [1 6 7 ... 1 9 5]
0.28323728813559323
Iteration:  20
[1 2 9 ... 0 9 9] [1 6 7 ... 1 9 5]
0.4788983050847458
Iteration:  30
[1 2 7 ... 0 9 9] [1 6 7 ... 1 9 5]
0.5501186440677966
Iteration:  40
[1 4 7 ... 1 9 9] [1 6 7 ... 1 9 5]
0.5995593220338983
Iteration:  50
[1 4 7 ... 1 9 9] [1 6 7 ... 1 9 5]
0.6362372881355932
Iteration:  60
[1 4 7 ... 1 9 9] [1 6 7 ... 1 9 5]
0.6568305084745762
Iteration:  70
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.658542372881356
Iteration:  80
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.6378305084745762
Iteration:  90
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.6484237288135594
Iteration:  100
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.6589661016949152
Iteration:  110
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.6691864406779661
Iteration:  120
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.6796271186440678
Iteration:  130
[1 2 7 ... 1 9 5] [1 6 7 ... 1 9 5]
0.688677966101695
Iteration:  140
[

In [231]:
df3 = pd.read_csv('C://Shaurya Games//New folder//fashion-mnist_test.csv')

df3 = np.array(df3)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

df3 = df3.T
Y_test = df3[0]
X_test = df3[1:n]
print(X_test)
X_test = X_test / 255.
_,m_train = X_test.shape

z1,a1,z2,a2=forward_prop(W1, b1, W2, b2, X_test)
predictions=get_predictions(a2)
get_accuracy(predictions, Y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 3 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[0 1 2 ... 8 6 2] [0 1 2 ... 8 8 1]


0.8184